In [1]:
import numpy as np

In [2]:
l = [23245, 27, 546, 215, -1234]

In [3]:
a = np.array(l)

In [4]:
a

array([23245,    27,   546,   215, -1234])

In [6]:
a[2:]

array([  546,   215, -1234])

In [7]:
a[2:4]

array([546, 215])

In [8]:
#when you slice a list, you are creating a new list
#when you slice an array, you are not creating a copy, you are working with the original array.

In [9]:
b= a[2:4]

In [10]:
b

array([546, 215])

In [11]:
b[0]

546

In [14]:
b[:] = 111

In [15]:
b

array([111, 111])

In [16]:
a

array([23245,    27,   111,   111, -1234])

In [17]:
#if we want to create a copy of an array, use copy() method
c = a.copy()

In [18]:
c

array([23245,    27,   111,   111, -1234])

In [20]:
c[0] = 0

In [21]:
c

array([    0,    27,   111,   111, -1234])

In [22]:
a

array([23245,    27,   111,   111, -1234])